apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result-service
    app: demo-voting-app
spec:
  type: NodePort      # external service
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30006
  selector:               # labels from result-app-pod
    name: result-app-pod
    app: demo-voting-app
